package hook

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	hookMarkerStart = "# >>> branchbase hook >>>"
	hookMarkerEnd   = "# <<< branchbase hook <<<"
)

var ErrNotGitRepository = errors.New("cannot install hooks: target directory is not a git repository")

// ScriptTemplate returns the shell snippet injected into .git/hooks/
func ScriptTemplate(hookName string) string {
	return fmt.Sprintf(`%s
# Auto-generated by BranchBase. Do not edit this block manually.
if command -v branchbase >/dev/null 2>&1; then
    branchbase hook-trigger %s "$@" >/dev/null 2>&1 &
fi
%s
`, hookMarkerStart, hookName, hookMarkerEnd)
}

// InstallHooks installs the post-checkout and post-merge hooks into .git/hooks
func InstallHooks(repoPath string) error {
	gitHooksDir := filepath.Join(repoPath, ".git", "hooks")
	info, err := os.Stat(filepath.Join(repoPath, ".git"))
	if err != nil || !info.IsDir() {
		return ErrNotGitRepository
	}

	if err := os.MkdirAll(gitHooksDir, 0755); err != nil {
		return fmt.Errorf("failed to create hooks directory: %w", err)
	}

	hooks := []string{"post-checkout", "post-merge"}
	for _, h := range hooks {
		hookFile := filepath.Join(gitHooksDir, h)
		if err := installSingleHook(hookFile, h); err != nil {
			return err
		}
	}

	return nil
}

func installSingleHook(hookPath, hookName string) error {
	var existingContent string
	if data, err := os.ReadFile(hookPath); err == nil {
		existingContent = string(data)
	}

	if strings.Contains(existingContent, hookMarkerStart) {
		// Already installed
		return nil
	}

	snippet := ScriptTemplate(hookName)
	var finalContent string
	if existingContent == "" {
		finalContent = "#!/bin/sh\n" + snippet
	} else {
		finalContent = existingContent + "\n" + snippet
	}

	return os.WriteFile(hookPath, []byte(finalContent), 0755)
}

// UninstallHooks cleanly removes BranchBase blocks from .git/hooks
func UninstallHooks(repoPath string) error {
	gitHooksDir := filepath.Join(repoPath, ".git", "hooks")
	hooks := []string{"post-checkout", "post-merge"}

	for _, h := range hooks {
		hookFile := filepath.Join(gitHooksDir, h)
		data, err := os.ReadFile(hookFile)
		if err != nil {
			continue
		}

		content := string(data)
		if !strings.Contains(content, hookMarkerStart) {
			continue
		}

		startIdx := strings.Index(content, hookMarkerStart)
		endIdx := strings.Index(content, hookMarkerEnd)
		if startIdx != -1 && endIdx != -1 {
			// Guard against corrupted or reversed markers (issue #12).
			// If markers are out of order, the slice would produce invalid
			// results or panic; warn and skip the file instead.
			if startIdx >= endIdx {
				fmt.Fprintf(os.Stderr, "⚠️  Corrupted hook markers in %s (end marker before start); skipping — please remove manually.\n", hookFile)
				continue
			}
			endIdx += len(hookMarkerEnd)
			if endIdx > len(content) {
				fmt.Fprintf(os.Stderr, "⚠️  Truncated hook markers in %s; skipping — please remove manually.\n", hookFile)
				continue
			}
			cleaned := content[:startIdx] + content[endIdx:]
			cleaned = strings.TrimSpace(cleaned)

			if cleaned == "#!/bin/sh" || cleaned == "" {
				_ = os.Remove(hookFile)
			} else {
				_ = os.WriteFile(hookFile, []byte(cleaned+"\n"), 0755)
			}
		}
	}

	return nil
}

// AreHooksInstalled checks whether BranchBase hooks are configured in the repository
func AreHooksInstalled(repoPath string) bool {
	postCheckout := filepath.Join(repoPath, ".git", "hooks", "post-checkout")
	data, err := os.ReadFile(postCheckout)
	if err != nil {
		return false
	}
	return strings.Contains(string(data), hookMarkerStart)
}
