package hook

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	hookMarkerStart = "# >>> branchbase hook >>>"
	hookMarkerEnd   = "# <<< branchbase hook <<<"
)

var ErrNotGitRepository = errors.New("cannot install hooks: target directory is not a git repository")

// ScriptTemplate returns the shell snippet injected into .git/hooks/
func ScriptTemplate(hookName string) string {
	return fmt.Sprintf(`%s
# Auto-generated by BranchBase. Do not edit this block manually.
if command -v branchbase >/dev/null 2>&1; then
    (nohup branchbase hook-trigger %s "$@" >/dev/null 2>&1 &)
fi
%s
`, hookMarkerStart, hookName, hookMarkerEnd)
}

// resolveGitHooksDir locates the actual hooks directory for both standard repositories
// and Git worktrees/submodules where .git is a pointer file (gitdir: ...).
func resolveGitHooksDir(repoPath string) (string, error) {
	gitPath := filepath.Join(repoPath, ".git")
	info, err := os.Stat(gitPath)
	if err != nil {
		return "", ErrNotGitRepository
	}

	if info.IsDir() {
		return filepath.Join(gitPath, "hooks"), nil
	}

	// .git is a file (common in git worktrees or submodules)
	content, err := os.ReadFile(gitPath)
	if err != nil {
		return "", ErrNotGitRepository
	}

	text := strings.TrimSpace(string(content))
	if !strings.HasPrefix(text, "gitdir: ") {
		return "", ErrNotGitRepository
	}

	gitDir := strings.TrimSpace(strings.TrimPrefix(text, "gitdir: "))
	if !filepath.IsAbs(gitDir) {
		gitDir = filepath.Join(repoPath, gitDir)
	}

	// In worktrees, gitDir is typically .git/worktrees/<name>.
	// If a commondir file exists, hooks reside in the common .git directory.
	commonDirPath := filepath.Join(gitDir, "commondir")
	if cBytes, err := os.ReadFile(commonDirPath); err == nil {
		cDir := strings.TrimSpace(string(cBytes))
		if !filepath.IsAbs(cDir) {
			cDir = filepath.Join(gitDir, cDir)
		}
		return filepath.Join(cDir, "hooks"), nil
	}

	return filepath.Join(gitDir, "hooks"), nil
}

// InstallHooks installs the post-checkout and post-merge hooks into .git/hooks
func InstallHooks(repoPath string) error {
	gitHooksDir, err := resolveGitHooksDir(repoPath)
	if err != nil {
		return err
	}

	if err := os.MkdirAll(gitHooksDir, 0755); err != nil {
		return fmt.Errorf("failed to create hooks directory: %w", err)
	}

	hooks := []string{"post-checkout", "post-merge"}
	for _, h := range hooks {
		hookFile := filepath.Join(gitHooksDir, h)
		if err := installSingleHook(hookFile, h); err != nil {
			return err
		}
	}

	return nil
}

func installSingleHook(hookPath, hookName string) error {
	var existingContent string
	if data, err := os.ReadFile(hookPath); err == nil {
		existingContent = string(data)
	}

	if strings.Contains(existingContent, hookMarkerStart) {
		// Already installed
		return nil
	}

	snippet := ScriptTemplate(hookName)
	var finalContent string
	if existingContent == "" {
		finalContent = "#!/bin/sh\n" + snippet
	} else {
		finalContent = existingContent + "\n" + snippet
	}

	if err := os.WriteFile(hookPath, []byte(finalContent), 0755); err != nil {
		return err
	}
	// Explicitly set executable bit: on Unix, os.WriteFile does not alter permissions on existing files
	_ = os.Chmod(hookPath, 0755)
	return nil
}

// UninstallHooks cleanly removes BranchBase blocks from .git/hooks
func UninstallHooks(repoPath string) error {
	gitHooksDir, err := resolveGitHooksDir(repoPath)
	if err != nil {
		return err
	}
	hooks := []string{"post-checkout", "post-merge"}

	for _, h := range hooks {
		hookFile := filepath.Join(gitHooksDir, h)
		data, err := os.ReadFile(hookFile)
		if err != nil {
			continue
		}

		content := string(data)
		if !strings.Contains(content, hookMarkerStart) {
			continue
		}

		startIdx := strings.Index(content, hookMarkerStart)
		endIdx := strings.Index(content, hookMarkerEnd)
		if startIdx == -1 || endIdx == -1 {
			continue
		}
		if startIdx > endIdx {
			return fmt.Errorf("corrupted branchbase hook markers in %s: end marker appears before start; fix or remove the file manually", hookFile)
		}
		endIdx += len(hookMarkerEnd)
		if endIdx > len(content) {
			return fmt.Errorf("corrupted branchbase hook markers in %s", hookFile)
		}
		cleaned := content[:startIdx] + content[endIdx:]
		cleaned = strings.TrimSpace(cleaned)

		if cleaned == "#!/bin/sh" || cleaned == "" {
			_ = os.Remove(hookFile)
		} else {
			if err := os.WriteFile(hookFile, []byte(cleaned+"\n"), 0755); err == nil {
				_ = os.Chmod(hookFile, 0755)
			}
		}
	}

	return nil
}

// AreHooksInstalled checks whether BranchBase hooks are configured in the repository
func AreHooksInstalled(repoPath string) bool {
	gitHooksDir, err := resolveGitHooksDir(repoPath)
	if err != nil {
		return false
	}
	postCheckout := filepath.Join(gitHooksDir, "post-checkout")
	data, err := os.ReadFile(postCheckout)
	if err != nil {
		return false
	}
	return strings.Contains(string(data), hookMarkerStart)
}

